version: 0.2

env:
  parameter-store:
    repository: "ECR_REPOSITORY"

phases:
  install:
    python: 3.9
  pre_build:
    commands:
      - echo ${repository}
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${repository}
  build:
    commands:
      - docker build . -t dockekr-fastapi
      - docker tag docker-fastapi:latest ${repository}/docker-fastapi:latest
      - docker tag docker-fastapi:latest ${repository}/docker-fastapi:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - docker push ${repository}/docker-fastapi:latest
      - docker push ${repository}/docker-fastapi:$CODEBUILD_RESOLVED_SOURCE_VERSION

