version: 0.2

env:
  parameter-store:
    repository: "ECR_REPOSITORY"

phases:
  install:
    python: 3.9
  pre_build:
    - echo ${repository}
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${repository}
  build:
    commands:
      - docker build . -t dockekr-fastapi
#  post_build:
#    pass


